In [1]:
sum = 0
n = 99
while n > 0:
    sum = sum + n
    n = n - 2
print(sum)

2500


In [2]:
from numpy import*  #导入numpy的库函数
import numpy as np  #使用numpy的函数时，以np.开头
arr=np.arange(15).reshape(3,5)
print(arr)
arr.T

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [3]:
L = [
    ['Apple', 'Google', 'Microsoft'],
    ['Java', 'Python', 'Ruby', 'PHP'],
    ['Adam', 'Bart', 'Lisa']
]
print(L[0][0])  #打印Apple
print(L[1][1])  #打印Python
print(L[2][2])  #打印Lisa

Apple
Python
Lisa


In [4]:
age = int(input('your age is '))
if age >= 18:
    print('adult')
elif age >=6:
    print('teenager')
else:
    print('kid')

your age is 20
adult


In [5]:
height = 1.75
weight = 80.5
bmi = weight/height/height  # BMI为体重（kg)除以身高（m）的平方
print('小明的BMI指数为:%.2f'%bmi)
if bmi < 18.5:
    print('过轻')
elif 18.5 <= bmi <= 25:
    print('正常')
elif 25 <= bmi <= 28:
    print('过重')
elif 28 <= bmi <= 32:
    print('肥胖')
else:
    print('严重肥胖')

小明的BMI指数为:26.29
过重


In [6]:
#求1-10总和
sum = 0
for x in [1,2,3,4,5,6,7,8,9,10]:
    sum = sum + x
print(sum)

55


In [7]:
#求1-100之和
sum = 0
for x in range(101):
    sum = sum + x
print(sum)

5050


In [8]:
#求100以内奇数之和
sum = 0
n = 1
while n < 100:
    sum = sum + n
    n = n + 2
print(sum)

2500


In [9]:
sum = 0
n = 99
while n > 0:
    sum = sum + n
    n = n - 2
print(sum)

2500


In [15]:
L = ['Bart', 'Lisa', 'Adam']  #打印名字
for name in L:
    print('Hello,%s!'%name)

Hello,Bart!
Hello,Lisa!
Hello,Adam!


In [16]:
n = 1
while n <= 100:
    if n >10:
        break   #结束当前循环
    print(n)
    n = n + 1
print('END')

1
2
3
4
5
6
7
8
9
10
END


In [17]:
n = 0
while n < 10:
    n = n + 1
    if n % 2 == 0:
        continue   #跳过直接继续下一轮循环
    print(n)

1
3
5
7
9


In [10]:
d = {'Michael': 95,'Bob': 75,'Tracy': 85}
d['Michael']

d['Adam']= 67
d['Adam']
d['Michael']
'Bob' in d
'Thomas' in d
d.get('Thomas',-1)

-1

In [12]:
s = set([1,2,3])
s

{1, 2, 3}

In [14]:
a = ['c','b','a']
a.sort()
a

['a', 'b', 'c']

In [17]:

help(abs)
abs(-100)
help(max)

Help on built-in function abs in module builtins:

abs(x, /)
    Return the absolute value of the argument.

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [23]:
#整数转换成十六进制数

n1 = 255
n2 = 1000
print(str(hex(n1)))
print(str(hex(n2)))

0xff
0x3e8


In [24]:
n1 = 255
n2 = 1000
n = [n1, n2]
for i in n:
    print('%d的十六进制表示为%s' %(i, hex(i)))

255的十六进制表示为0xff
1000的十六进制表示为0x3e8
